console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
betterBlue = '#536dfe'
orange = '#FF5733'

[secondary_prompt]
template = '❯❯ '
foreground = 'blue'
background = 'transparent'

[transient_prompt]
template = '❯ '
background = 'transparent'
foreground_templates = [
  '{{if gt .Code 0}}red{{end}}',
  '{{if eq .Code 0}}blue{{end}}',
]

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
template = '{{ .Path }}'
foreground = 'p:orange'
background = 'transparent'
type = 'path'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'
style = 'full'

[[blocks.segments]]
template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'
foreground = 'p:grey'
background = 'transparent'
type = 'git'
style = 'plain'

[blocks.segments.properties]
branch_icon = ''
cache_duration = 'none'
commit_icon = '@'
fetch_status = true

[[blocks]]
type = 'rprompt'
overflow = 'hidden'

[[blocks.segments]]
template = '{{ .FormattedMs }}'
foreground = 'yellow'
background = 'transparent'
type = 'executiontime'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'
threshold = 5000
[[blocks.segments]]
type = "python"
style = "powerline"
powerline_symbol = ""
foreground = "#100e23"
background = "#906cff"
template = "{{ .Full }} {{ if .Venv }}{{ .Venv }} {{ end }}"
[[blocks.segments]]
type = "kubectl"
style = "powerline"
powerline_symbol = ""
foreground = "#000000"
background = "#ebcc34"
template = "{{.Context}}{{if .Namespace}}::{{.Namespace}}{{end}} "


[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
template = '❯'
background = 'transparent'
type = 'text'
style = 'plain'
foreground_templates = [
  '{{if gt .Code 0}}red{{end}}',
  '{{if eq .Code 0}}p:betterBlue{{end}}',
]

[blocks.segments.properties]
cache_duration = 'none'
